"use client"
// import type { Metadata } from "next";
import "./globals.css";
import Header from "./components/header"
import 'bootstrap/dist/css/bootstrap.min.css';


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const handleTopicClick = (topic: string) => {
    console.log(topic);
  }
  return (
    <html lang="en">
      <body>
        <Header handleTopicClick={handleTopicClick}/>
        {children}
      </body>
    </html>
  );
}
